apps/diet_web/lib/diet_web/router.ex
defmodule DietWeb.Router do
  use DietWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DietWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DietWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/newsfeed", PageController, :newsfeed
    live "/search", SearchLive
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/reports", ReportController, only: [:create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show

    get "/sitemap.xml", SitemapController, :sitemap
  end

  scope "/manage", DietWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
    resources "/articles", ArticleController
  end

  scope "/admin", DietWeb do
    pipe_through [:browser, :authenticate_user, :authenticate_admin_user]

    get "/videos", AdminController, :videos
    patch "/videos/:id/actions/publish", AdminController, :publish
    patch "/videos/:id/actions/unpublish", AdminController, :unpublish
  end
end

apps/diet_web/lib/diet_web/views/layout_view.ex
defmodule DietWeb.LayoutView do
  use DietWeb, :view
end

apps/diet_web/lib/diet_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= render DietWeb.LayoutView, "seo_metadata.html", assigns %>
    <title>Weight Hater</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <!-- Google fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Alegreya:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- We want to export the userToken before to load the rest of the scripts -->
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
  </head>
  <body>
    <header>
      <%= render DietWeb.LayoutView, "navigation.html", assigns %>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <%= render DietWeb.LayoutView, "footer.html", assigns %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/diet_web/lib/diet_web/templates/layout/footer.html.eex
<footer class="bg-light mt-2">
  <div class="footer-copyright text-center py-3">
    <p>© Weight Hater 2019</p>
  </div>
</footer>

apps/diet_web/lib/diet_web/templates/layout/navigation.html.eex
<nav class="navbar navbar-expand-lg bg-light navbar-light fixed-top">
  <div class="container">
    <%= link to: Routes.page_path(@conn, :index), class: "navbar-brand" do %>
      <%= img_tag Routes.static_path(@conn, "/images/logo_transparent.png"), class: "navbar-logo d-inline-block align-top", alt: "Weight Hater Logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <%= if @current_user do %>
          <li class="nav-item"><%= link "Search", to: Routes.live_path(@conn, DietWeb.SearchLive), class: "nav-link" %></li>
          <li class="nav-item"><%= link "News Feed", to: Routes.page_path(@conn, :newsfeed), class: "nav-link"%></li>
          <li class="nav-item"><%= link "My Videos", to: Routes.video_path(@conn, :index), class: "nav-link" %></li>
          <li class="nav-item"><%= link "My Articles", to: Routes.article_path(@conn, :index), class: "nav-link" %></li>
          <%= if @current_user.admin do %>
            <li class="nav-item">
              <%= link "All Users", to: Routes.user_path(@conn, :index), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link "All Videos", to: Routes.admin_path(@conn, :videos), class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link "Log out",
            to: Routes.session_path(@conn, :delete, @current_user), class: "nav-link",
            method: "delete" %>
          </li>
        <% else %>
          <li class="nav-item"><%= link "News Feed", to: Routes.page_path(@conn, :newsfeed), class: "nav-link" %></li>
          <li class="nav-item"><%= link "Register", to: Routes.user_path(@conn, :new), class: "nav-link" %></li>
          <li class="nav-item"><%= link "Log in", to: Routes.session_path(@conn, :new), class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

apps/diet_web/lib/diet_web/templates/layout/seo_metadata.html.eex
<!-- Yandex -->
<meta name="yandex-verification" content="ba77a5ca3b3bb297" />