apps/diet_web/lib/diet_web/router.ex
defmodule DietWeb.Router do
  use DietWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DietWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DietWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/newsfeed", PageController, :newsfeed
    live "/search", SearchLive
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/reports", ReportController, only: [:create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show

    get "/sitemap.xml", SitemapController, :sitemap
  end

  scope "/manage", DietWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/videos", VideoController
    resources "/articles", ArticleController
  end

  scope "/admin", DietWeb do
    pipe_through [:browser, :authenticate_user, :authenticate_admin_user]

    get "/videos", AdminController, :videos
    patch "/videos/:id/actions/publish", AdminController, :publish
    patch "/videos/:id/actions/unpublish", AdminController, :unpublish
  end
end

apps/diet_web/lib/diet_web/templates/page/article.html.leex
<div class="card text-center mb-3">
  <div class="card-body">
    <h5 class="card-title">
      <p><%= @article.title %></p>
      <a href="<%= @article.url %>" target="_blank">
        <i class="material-icons launch">launch</i>
      </a>
    </h5>
  </div>
  <div class="embed-responsive embed-responsive-21by9">
    <embed src="<%= @article.url %>" type="<%= @article.type || "html/text" %>"></embed>
  </div>
  <div class="card-footer">
    <div class="float-sm-left">
      <%= if @current_user do %>
        <i class="material-icons arrow-upward" phx-click="like" phx-value-id="<%= @article.id %>" phx-value-type="<%= reportable_type(@article) %>">arrow_upward</i>
        <span class="badge badge-pill badge-secondary"><%= Map.get(@like_counts, {@article.id, reportable_type(@article)}, 0) %></span>
        <i class="material-icons arrow-downward" phx-click="unlike" phx-value-id="<%= @article.id %>" phx-value-type="<%= reportable_type(@article) %>">arrow_downward</i>
        <i class="material-icons report" data-toggle="modal" data-target="#reportModal<%= reportable_type(@article) %><%= @article.id %>">report</i>
      <% else %>
        <span class="badge badge-pill badge-secondary"><%= Map.get(@like_counts, {@article.id, reportable_type(@article)}, 0) %></span>
      <% end %>
    </div>
    <div class="float-sm-right">
      <small class="text-muted">
        <%= "Published #{posted_on(@article.published_at)} by " %>
        <%= link @article.user.username, to: Routes.user_path(DietWeb.Endpoint, :show, @article.user) %>
      </small>
    </div>
  </div>
</div>
<%= render "report_modal.html", Map.put(assigns, :reportable, @article) %>

apps/diet_web/lib/diet_web/templates/page/coming_soon.html.leex
<div class="card mb-3">
  <%= img_tag Routes.static_path(DietWeb.Endpoint, "/images/coming_features_background.jpg"), class: "card-img-top", alt: "Coming Soon Image" %>
  <div class="card-header text-center">
  <h4>Coming Soon</h4>
  </div>
  <ol class="list-group list-group-flush">
    <li class="list-group-item d-flex justify-content-between align-items-center">
      New posts live update
      <span class="badge badge-pill badge-warning">In Progress</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Higher quality newsfeed
      <span class="badge badge-pill badge-warning">In Progress</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      User profile page
      <span class="badge badge-pill badge-info">Shortly</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Interactive way of watching videos
      <span class="badge badge-pill badge-info">Shortly</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Fitness/Training search
      <span class="badge badge-pill badge-secondary">Unscheduled</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Diet/Nutrition search
      <span class="badge badge-pill badge-secondary">Unscheduled</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Food recipes search
      <span class="badge badge-pill badge-secondary">Unscheduled</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      Rate best content for the month
      <span class="badge badge-pill badge-secondary">Unscheduled</span>
    </li>
  </ol>
</div>

apps/diet_web/lib/diet_web/templates/page/filters.html.leex
<div class="card mb-3">
  <div class="card-header text-center">
  <h4>Tags</h4>
  </div>
  <%= f = form_for  %Ecto.Changeset{}, "#", [as: :filters, phx_change: :select] %>
    <%= multiple_select f, :tags, [all: nil] ++ tags_select_options(@tags), selected: @selected_tag_ids, class: "form-control" %>
  </form>
</div>

apps/diet_web/lib/diet_web/templates/page/index.html.eex
<section>
  <h1><%= gettext "Welcome to %{name}!", name: "Weight Hater" %></h1>
  <div class="jumbotron">
    <p>Diet consistently and cheat rarely!!!</p>
  </div>
</section>

apps/diet_web/lib/diet_web/templates/page/infinite_scroll.html.leex
<div class="text-center">
  <%= if @next_cursor do %>
  <a href="#" id="infinite-scroll-target" phx-click="load-more" phx-value-cursor=<%= @next_cursor %>>
    <div class="spinner-border spinner-border-sm text-secondary d-none" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </a>
  <% end %>
</div>

<script>
  function triggerClick(entries, observer) {
    let elem = entries[0];

    if(elem && elem.isIntersecting) {
      elem.target.click();
      elem.target.children[0].classList.remove('d-none');
    }
  };
  (new IntersectionObserver(triggerClick, {root: null, threshold: 1})).observe(document.querySelector('#infinite-scroll-target'));
</script>

apps/diet_web/lib/diet_web/templates/page/newest_articles.html.leex
<div class="card mb-3">
  <div class="card-header text-center">
  <h4>Newest Articles</h4>
  </div>
  <ul class="list-group list-group-flush">
    <%= for article <- @newest_articles do %>
      <li class="list-group-item d-flex justify-content-between align-items-center text-truncate">
        <a href="<%= article.url %>" target="_blank">
          <span><%= article.title %></span>
        </a>
      </li>
    <% end %>
  </ul>
</div>

apps/diet_web/lib/diet_web/templates/page/newest_posts.html.leex
<div class="card mb-3">
  <div class="card-header text-center">
  <h4>Newest Videos</h4>
  </div>
  <ul class="list-group list-group-flush">
    <%= for video <- @newest_videos do %>
      <li class="list-group-item d-flex justify-content-between align-items-center text-truncate">
      <%= link video.title, to: Routes.watch_path(@socket, :show, video) %>
      </li>
    <% end %>
  </ul>
</div>

apps/diet_web/lib/diet_web/templates/page/newest_videos.html.leex
<div class="card mb-3">
  <div class="card-header text-center">
  <h4>Newest Videos</h4>
  </div>
  <ul class="list-group list-group-flush">
    <%= for video <- @newest_videos do %>
      <li class="list-group-item d-flex justify-content-between align-items-center text-truncate">
      <%= link video.title, to: Routes.watch_path(@socket, :show, video) %>
      </li>
    <% end %>
  </ul>
</div>

apps/diet_web/lib/diet_web/templates/page/newsfeed.html.eex
<div class="newsfeed">
  <h2>Popular videos</h2>
  <ul class="newsfeed-popular-videos">
  <%= for video <- @videos do %>
    <li>
      <div>
        <h4><%= video.title %><h4>
        <iframe class="newsfeed-iframe-player" src="<%= embedded_url(video) %>" allowfullscreen>
        </iframe>
      </div>
    </li>
  <% end %>
  </ul>
</div>

apps/diet_web/lib/diet_web/templates/page/newsfeed.html.leex
<div class="container mt-3">
  <div class="row">
    <div class="col-md-4 order-md-2">
      <%= render "coming_soon.html", assigns %>
      <%= render "filters.html", assigns %>
      <%= render "newest_videos.html", assigns %>
      <%= render "newest_articles.html", assigns %>
    </div>

    <div class="col-md-8 order-md-1">
      <%= for article <- @articles do %>
        <%= render "article.html", Map.put(assigns, :article, article) %>
      <% end %>
      <%= for video <- @videos do %>
        <%= render "video.html", Map.put(assigns, :video, video) %>
      <% end %>
      <%= render "infinite_scroll.html", assigns %>
    </div>
  </div>
</div>

apps/diet_web/lib/diet_web/templates/page/report_modal.html.leex
<div class="modal fade" id="reportModal<%= reportable_type(@reportable) %><%= @reportable.id %>" tabindex="-1" role="dialog" aria-labelledby="reportModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reportModalTitle">Report</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for :report, Routes.report_path(DietWeb.Endpoint, :create), [csrf_token: @csrf_token], fn f -> %>
          <%= hidden_input f, :reportable_id, value: @reportable.id %>
          <%= hidden_input f, :reportable_type, value: reportable_type(@reportable) %>
          <div class="form-group">
            <%= select f, :reason, ["It's spam or abuse": "spam_or_abuse", "I'm not interested in this post": "not_interested"], class: "icustom-select" %>
          </div>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= submit "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

apps/diet_web/lib/diet_web/templates/page/video.html.leex
<div class="card text-center mb-3">
  <div class="card-body">
    <h5 class="card-title">
      <%= link @video.title, to: Routes.watch_path(@socket, :show, @video) %>
    </h5>
  </div>
  <div class="embed-responsive embed-responsive-21by9">
    <iframe class="embed-responsive-item" src="<%= embedded_url(@video) %>" allowfullscreen></iframe>
  </div>
  <div class="card-footer">
    <div class="float-sm-left">
      <%= if @current_user do %>
        <i class="material-icons arrow-upward" phx-click="like" phx-value-id="<%= @video.id %>" phx-value-type="<%= reportable_type(@video) %>">arrow_upward</i>
        <span class="badge badge-pill badge-secondary"><%= Map.get(@like_counts, {@video.id, reportable_type(@video)}, 0) %></span>
        <i class="material-icons arrow-downward" phx-click="unlike" phx-value-id="<%= @video.id %>" phx-value-type="<%= reportable_type(@video) %>">arrow_downward</i>
        <i class="material-icons report" data-toggle="modal" data-target="#reportModal<%= reportable_type(@video) %><%= @video.id %>">report</i>
      <% else %>
        <span class="badge badge-pill badge-secondary"><%= Map.get(@like_counts, {@video.id, reportable_type(@video)}, 0) %></span>
      <% end %>
    </div>
    <div class="float-sm-right">
      <small class="text-muted">
        <%= "Published #{posted_on(@video.published_at)} by " %>
        <%= link @video.user.username, to: Routes.user_path(DietWeb.Endpoint, :show, @video.user) %>
      </small>
    </div>
  </div>
</div>
<%= render "report_modal.html", Map.put(assigns, :reportable, @video) %>